config/routes.rb
Paporeto::Application.routes.draw do

  # Uploadbox
  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  # Uploadbox
  devise_for :users

  # Admin ------------------------------------------------------------------------
  namespace :admin do
    resources :categories, except: :show
    resources :articles
    resources :users, except: :show

    root 'articles#index'
  end

  # Public ------------------------------------------------------------------------

  resources :categories, path: 'artigos', only: [] do
    resources :articles, path: '', only: [:index, :show]
  end

  resources :suggested_articles, only: [:new, :create]

  root 'home#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :category, :published_at, presence: true
  belongs_to :category
  uploads_one :image, thumb: [90, 80], small: [260, 195], regular: [580, 240], big: [940, 388], full: [1280, 493]

  def to_param
    "#{id} #{title}".parameterize
  end

  def related_articles
    category.articles.order(published_at: :desc).where.not(id: id)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout 'admin'

  # GET /articles
  def index
    @articles = Article.order(featured_at_home: :desc).order(featured: :desc).order(published_at: :desc).order(:title)
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to [:admin, @article], notice: 'Artigo salvo.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to [:admin, @article], notice: 'Artigo salvo.'
    else
      render action: 'edit'
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Artigo excluído.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :body, :published_at, :category_id, :image, :summary, :featured, :featured_at_home)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_category

  def index
    @articles = @category.articles.limit(8)
    @featured_article = @category.featured_article
  end

  def show
    @article = Article.find(params[:id])
    @related_articles = @article.related_articles
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
end

app/views/admin/articles/_form.html.slim
= simple_form_for([:admin, @article]) do |f|
  = f.error_notification

  .form-inputs
    = f.uploads_one :image, preview: :regular
    = f.input :title
    = f.input :summary
    = f.association :category, prompt: 'Selecione'
    = f.input :body
    = f.input :published_at
    = f.input :featured
    = f.input :featured_at_home

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/articles/edit.html.slim
h1 Editar artigo

== render 'form'

app/views/admin/articles/index.html.slim
h1 Artigos

table.table.table-striped
  thead
    tr
      th Título
      th Publicado em
      th Categoria
      th Destaque
      th Home
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = l article.published_at
        td = article.category.name
        td = article.featured ? 'Sim' : 'Não'
        td = article.featured_at_home ? 'Sim' : 'Não'
        td
          .btn-group.pull-right
            = link_to 'Ver', [:admin, article], class: 'btn btn-default btn-sm'
            = link_to 'Editar', edit_admin_article_path(article), class: 'btn btn-default btn-sm'
            = link_to 'Excluir', [:admin, article], :confirm => 'Tem certeza?', :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Criar Artigo', new_admin_article_path, class: 'btn btn-primary'

app/views/admin/articles/new.html.slim
h1 Novo artigo

== render 'form'

app/views/admin/articles/show.html.slim
h1 
  = @article.title
  .pull-right
    = link_to 'Editar', edit_admin_article_path(@article), class: 'btn btn-default'

p = @article.summary
hr

strong = @article.category.name
p = l @article.published_at

p = img @article.image.regular if @article.image?
= simple_format @article.body