config/routes.rb
Paporeto::Application.routes.draw do

  # Uploadbox
  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  # Uploadbox
  devise_for :users

  # Admin ------------------------------------------------------------------------
  namespace :admin do
    resources :categories, except: :show
    resources :articles
    resources :users, except: :show

    root 'articles#index'
  end

  # Public ------------------------------------------------------------------------

  resources :categories, path: 'artigos', only: [] do
    resources :articles, path: '', only: [:index, :show]
  end

  resources :suggested_articles, only: [:new, :create]

  root 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :articles

  def to_param
    "#{id} #{name}".parameterize
  end

  def slug
    name.parameterize
  end

  def featured_article
    articles.where(featured: true).first
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  layout 'admin'
  
  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to admin_categories_url
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/admin/categories/_form.html.slim
= simple_form_for([:admin, @category]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/categories/edit.html.slim
h1 Editar categoria

== render 'form'

app/views/admin/categories/index.html.slim
h1 Categorias

table.table.table-striped
  thead
    tr
      th Nome
      th
  
  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td 
          .btn-group.pull-right
            = link_to 'Editar', edit_admin_category_path(category), class: 'btn btn-default btn-sm'
            = link_to 'Excluir', [:admin, category], :confirm => 'Tem certeza?', :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Nova Categoria', new_admin_category_path, class: 'btn btn-primary'

app/views/admin/categories/new.html.slim
h1 Nova categoria

== render 'form'