config/routes.rb
Paporeto::Application.routes.draw do

  # Uploadbox
  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  # Uploadbox
  devise_for :users

  # Admin ------------------------------------------------------------------------
  namespace :admin do
    resources :categories, except: :show
    resources :articles
    resources :users, except: :show

    root 'articles#index'
  end

  # Public ------------------------------------------------------------------------

  resources :categories, path: 'artigos', only: [] do
    resources :articles, path: '', only: [:index, :show]
  end

  resources :suggested_articles, only: [:new, :create]

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  layout 'admin'
  
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if user_params[:password].blank?
      @user.update_without_password(user_params_without_password)
    else
      @user.update(user_params)
    end

    if @user.valid?
      if @user == current_user
        sign_in(@user, bypass: true)
      end

      redirect_to admin_users_url
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'Usuário excluído.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def user_params_without_password
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if user_params[:password].blank?
      @user.update_without_password(user_params_without_password)
    else
      @user.update(user_params)
    end

    if @user.valid?
      if @user == current_user
        sign_in(@user, bypass: true)
      end

      redirect_to users_url
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuário excluído.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def user_params_without_password
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
    end
end

app/views/admin/users/_form.html.slim
= simple_form_for([:admin, @user]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 Editar usuário

== render 'form'

app/views/admin/users/index.html.slim
h1 Usuários

table.table.table-striped
  thead
    tr
      th Nome
      th Email
      th
  tboby
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td
          .btn-group.pull-right 
            = link_to 'Editar', edit_admin_user_path(user), class: 'btn btn-default btn-sm'
            = link_to 'Excluir', [:admin, user], data: {:confirm => 'Tem certeza?'}, :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Criar usuário', new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.slim
h1 Criar usuário

== render 'form'