config/routes.rb
Paporeto::Application.routes.draw do

  # Uploadbox
  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  # Uploadbox
  devise_for :users

  # Admin ------------------------------------------------------------------------
  namespace :admin do
    resources :categories, except: :show
    resources :articles
    resources :users, except: :show

    root 'articles#index'
  end

  # Public ------------------------------------------------------------------------

  resources :categories, path: 'artigos', only: [] do
    resources :articles, path: '', only: [:index, :show]
  end

  resources :suggested_articles, only: [:new, :create]

  root 'home#index'
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Paporeto
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags

    /[if lt IE 9]
      = javascript_include_tag "html5shiv", "data-turbolinks-track" => true
      = javascript_include_tag "respond.min", "data-turbolinks-track" => true
  body
    - if user_signed_in?
      .navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
             = link_to 'Paporeto', '#', class: 'navbar-brand'
          .navbar-collapse
            ul.nav.navbar-nav
              li class="#{nav_status('articles')}" = link_to 'Artigos', admin_articles_path
              li class="#{nav_status('categories')}" = link_to 'Categorias', admin_categories_path
              li class="#{nav_status('users')}" = link_to 'Usuários', admin_users_path
            ul.nav.navbar-nav.pull-right
              li = link_to current_user.name, edit_admin_user_path(current_user)
              li = link_to 'Sair', destroy_user_session_path, method: :delete

    .container
      - if notice
        .alert.alert-info.alert-dismissable
          button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times; 
          = notice

      = yield
    = javascript_include_tag "admin", "data-turbolinks-track" => true

app/views/layouts/application.slim
doctype html
/[if lt IE 7]
  | <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang='pt-br'>
/[if IE 7]
  | <html class="no-js lt-ie9 lt-ie8" lang='pt-br'>
/[if IE 8]
  | <html class="no-js lt-ie9" lang='pt-br'>
/[if IE 9]
  | <html class="no-js ie ie9" lang='pt-br'>
| <!--[if (gte IE 9)|!(IE)]<!-->
html.no-js lang='pt-br'
  | <!--<![endif]-->
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    title PapoReto.com — Notícias direto ao ponto, sem enrolação!
    meta name='author' content='Startaê — http://www.startae.com.br'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico', type: 'image/x-icon'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  body class='#{@page_class}'
    = render 'shared/header'
    = yield
    = render 'shared/footer'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true